name: Neqm_mntget

on:
  # schedule:
  #   - cron: '0 3 * * *'
  #   - cron: '0 9 * * *'
  #   - cron: '0 15 * * *'
  push:

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Japanese
        run: |
          sudo apt install fonts-noto

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run a one-line script
        run: python src/main.py

        env:
          DISTOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISIMO: ${{ secrets.DISID_IMO }}
          DISTKT: ${{ secrets.DISID_TKT }}
          LGMAIL: ${{ secrets.LG_MAIL }}
          LGPASS: ${{ secrets.LG_PASS }}
          LGURL: ${{ secrets.LG_URL }}
          TARURL: ${{ secrets.TARGET_URL }}

      - name: commit files
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add savepoint.txt
          git commit -m 'update savepoint.txt'
          git push origin main
